In [4]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

# a.
temp_adjusted = temperature + 2
print(temp_adjusted)

# b.
fahrenheit = (temperature * 9 / 5) + 32
print(fahrenheit)
# c.
greater_than_32 = temperature[temperature > 32]
print(greater_than_32)

# d.
count_exceed_32 = np.sum(temperature > 32)
print(count_exceed_32)

[27 30 33 37 40 29 35 42]
[ 77.   82.4  87.8  95.  100.4  80.6  91.4 104. ]
[35 38 33 40]
4


In [6]:
import numpy as np

steps = np.array(
    [
        [5000, 6200, 7100],
        [8000, 7500, 9000],
        [4500, 5100, 4800],
        [9000, 8500, 9500],
    ]
)

# a.
total_steps = np.sum(steps)
print(total_steps)

# b.
mean_steps = np.mean(steps)
print(mean_steps)

# c.
max_val = np.max(steps)
min_val = np.min(steps)
print(max_val)
print(min_val)

# d.
daily_totals = np.sum(steps, axis=0)
print(daily_totals)

# e.
user_totals = np.sum(steps, axis=1)
print(user_totals)

# f.
flat_idx = np.argmax(steps)
user_idx, day_idx = np.unravel_index(flat_idx, steps.shape)
print(user_idx)
print(day_idx)

84200
7016.666666666667
9500
4500
[26500 27300 30400]
[18300 24500 14400 27000]
3
2


In [7]:
import numpy as np

# a.
original = np.array([1, 2, 3, 4, 5, 6])

# b.
subset = original[1:5]

# c.
subset[0] = 999
print("c. Original:", original)
print("c. Subset:", subset)

# d.
subset_copy = original[1:5].copy()
subset_copy[0] = 500
print("d. Original:", original)
print("d. Copied:", subset_copy)

# e.
matrix_3x4 = np.arange(1, 13).reshape(3, 4)

# f.
first_row = matrix_3x4[0]
last_row = matrix_3x4[-1]
second_col = matrix_3x4[:, 1]
sub_matrix = matrix_3x4[0:2, 1:3]

# g.
flat_array = matrix_3x4.flatten()
ravel_array = matrix_3x4.ravel()

# h.
ravel_array[0] = 888
print("h. Matrix after modifying ravel():\n", matrix_3x4)

# i.
flat_array[0] = 777
print("i. Matrix after modifying flatten():\n", matrix_3x4)

# j.
print("j. Shape:", matrix_3x4.shape)
print("j. Dimensions:", matrix_3x4.ndim)
print("j. Size:", matrix_3x4.size)
print("j. Dtype:", matrix_3x4.dtype)

c. Original: [  1 999   3   4   5   6]
c. Subset: [999   3   4   5]
d. Original: [  1 999   3   4   5   6]
d. Copied: [500   3   4   5]
h. Matrix after modifying ravel():
 [[888   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
i. Matrix after modifying flatten():
 [[888   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
j. Shape: (3, 4)
j. Dimensions: 2
j. Size: 12
j. Dtype: int64


In [13]:
import numpy as np

X = np.array([[6, 70, 3], [5, 50, 6], [8, 80, 2], [4, 30, 8]])

y = np.array([40, 65, 30, 85])

# a.
shape_X = X.shape
dim_X = X.ndim
print("Shape of X:", shape_X)
print("Dimensions of X:", dim_X)

# b.
X_T = X.T
print("b. Transpose of X:\n", X_T)

# c.
XT_X = X_T @ X
print("c. X^T * X:\n", XT_X)

# d.
inv_XT_X = np.linalg.inv(XT_X)
print("d. Inverse of X^T * X:\n", inv_XT_X)

# e.
beta = np.linalg.inv(X.T @ X) @ X.T @ y
print("e. Coefficients (beta):", beta)

# g.
new_user = np.array([5, 40, 7])
predicted_score = new_user @ beta
print("Predicted score for the new user:", predicted_score)

Shape of X: (4, 3)
Dimensions of X: 2
b. Transpose of X:
 [[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
c. X^T * X:
 [[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]
d. Inverse of X^T * X:
 [[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]
e. Coefficients (beta): [-0.15921454  0.14083853 10.06302242]
Predicted score for the new user: 75.27862544778861
