In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

add_2 = arr + 2
print(add_2)

mul_3 = arr * 3
print(mul_3)

div_2 = arr / 2
print(div_2)

[12 22 32 42 52]
[ 30  60  90 120 150]
[ 5. 10. 15. 20. 25.]


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)

def find_most_frequent_and_indices(a):
    counts = np.bincount(a)
    most_freq_val = np.argmax(counts)
    indices = np.where(a == most_freq_val)[0]
    return most_freq_val, indices

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
freq_val_x, indices_x = find_most_frequent_and_indices(x)
print(freq_val_x, indices_x)

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
freq_val_y, indices_y = find_most_frequent_and_indices(y)
print(freq_val_y, indices_y)

[5 4 6 3 2 1]
1 [0 5 7 8 9]
1 [0 1 2]


In [3]:
import numpy as np

arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

elem_1_2 = arr[0, 1]
print(elem_1_2)

elem_3_1 = arr[2, 0]
print(elem_3_1)

20
70


In [4]:
import numpy as np

mukul = np.linspace(10, 100, 25)

print(mukul.ndim)
print(mukul.shape)
print(mukul.size)
print(mukul.dtype)
print(mukul.nbytes)

transposed_reshape = mukul.reshape(-1, 1)
print(transposed_reshape)

transposed_T = mukul.T
print(transposed_T)

1
(25,)
25
float64
200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [5]:
import numpy as np

ucs420_mukul = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print(np.mean(ucs420_mukul))
print(np.median(ucs420_mukul))
print(np.max(ucs420_mukul))
print(np.min(ucs420_mukul))
print(np.unique(ucs420_mukul))

reshaped_ucs420_mukul = ucs420_mukul.reshape(4, 3)
print(reshaped_ucs420_mukul)

resized_ucs420_mukul = np.resize(ucs420_mukul, (2, 3))
print(resized_ucs420_mukul)

43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
